### ISSUE TITLE
我最进也在重写校史

### ISSUE THREAD

**Issue by yyypasserby** [lavende/seu-history#1]
你把这个部署一下吧？看看效果。

**Comment by yyypasserby** [comment]
把版本和所用的库freeze一下吧，把requirements.txt push下？最新的django目录怎么变这样了。

**Comment by yyypasserby** [comment]
这个webapp写的很好，有种django best practice的感觉，架构很清晰。最近有个想法，我觉得我们可以把校史搞一个organization然后把我们的各个版本的校史推到这个organization里面，可以留个存档，方便参考和留档。

**Comment by huozhi** [comment]
这个还没很多没写完，python lib都只用了django和build-in的lib，等差不多了再部署。结构是我自己设计的，不是django默认目录

**Comment by huozhi** [comment]
你开一个org吧，把我拉进去^_^

**Comment by yyypasserby** [comment]
Ok，发现你用的还是那个hex方法的时候，好开心。

**Comment by huozhi** [comment]
嗯，只是做了细微的改变，基本原理都是一样的，要跟original版本保持一致嘛哈哈哈^_^
