### ISSUE TITLE
render需要手动update csrf token吗？

### ISSUE THREAD

**Issue by yyypasserby** [lavende/seu-history#2]
我怎么记得render本身就是用的RequestContext，不用再手动update csrf。望讨论。

**Comment by huozhi** [comment]
我理解是都是一个dict，我只是把所有dict集中在一个dict里作为一个RequestContext

**Comment by yyypasserby** [comment]
对，我就是觉得如果你用的是render的话，context是不是可以不用update(crsf(request))，因为我记得默认调用的是requestcontext，而requestcontext会默认调用csrf的更新函数。如果你的返回不是render那就应该要update。

**Comment by huozhi** [comment]
好的，我修改一下。谢谢提醒

**Comment by yyypasserby** [comment]
你先试一下。我不是特别清楚现在的用法了。^_^

**Comment by huozhi** [comment]
http://stackoverflow.com/questions/17408947/python-render-with-csrf-protection
应该是默认调用的
